### ISSUE TITLE
Merge ArcCheck and MapCheck parsers?

### ISSUE THREAD

**Issue by mchamberland** [cutright/IMRT-QA-Data-Miner#13]
As far as I can tell, MapCheck and ArcCheck reports are identical, except for the name at the top of the report (MapCheck or ArcCheck).

Should we merge the two parsers into one, then?

I have a few cases that even though we acquired two ArcCheck measurements, the report of the combined results show "MapCHECK" at the top of the report... We'd need to re-work the way it determines the report type to allow both ArcCheck and MapCheck, in any upper/lower case combination.

**Comment by cutright** [comment]
I think that's generally true.  I'll give it a spin on MapCheck and ArcCheck reports here.
