### ISSUE TITLE
Skip over invalid data in trending

### ISSUE THREAD

**Issue by mchamberland** [cutright/IMRT-QA-Data-Miner#15]
The following two lines ([here ](https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/trending_delta4.py#L276 )and [here](https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/trending_arccheck.py#L124)) raise a `ValueError` when the conversion to float fails.

What do you think of the following fix?

```python
if 'Any' in active_gamma or gamma_crit in active_gamma:
   try:
      y_float = float(self.data[select_y.value][i])
   except ValueError:
      continue
   new_data['x'].append(self.x[i])
   new_data['y'].append(y_float)
   new_data['id'].append(self.data['Patient ID'][i])
```

**Comment by mchamberland** [comment]
This comes from the gamma index statistics in my SNC Patient reports. If the statistics were not calculated, they are set to 'n/a' or 'NA'.

**Comment by mchamberland** [comment]
To save a line, we could also do:

```python
if 'Any' in active_gamma or gamma_crit in active_gamma:
   try:
      new_data['y'].append(float(self.data[select_y.value][i]))
   except ValueError:
      continue
   new_data['x'].append(self.x[i])
   new_data['id'].append(self.data['Patient ID'][i])
```

**Comment by cutright** [comment]
Went ahead and pushed that fix to master.  Thanks!
