### ISSUE TITLE
Selecting gamma criteria other than "Any" produces empty plot

### ISSUE THREAD

**Issue by mchamberland** [cutright/IMRT-QA-Data-Miner#23]
When I unselect "Any" then select another gamma criteria to plot, I get an `IndexError: list index out of range` on [line 302 of trending_arccheck.py.](https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/IQDM/trending_arccheck.py#L302).

It looks like by the time it gets to that line, the x and y lists are empty.

**Comment by mchamberland** [comment]
Found the bug:

[Line 122 in trending_arccheck.py](https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/IQDM/trending_arccheck.py#L122)

This returns, for example, "3%/3mm", but this gets compared to "3.0%/3.0mm", which is not the same string.

**Comment by mchamberland** [comment]
I think a similar bug is present in [trending_delta4.py](https://github.com/cutright/IMRT-QA-Data-Miner/blob/master/IQDM/trending_delta4.py#L265).

**Comment by cutright** [comment]
I think I caught that in my NM branch. 

There’s a new gamma selection set up there too so you plot only reports that are not any of 2/2, 3/2, etc.

**Comment by mchamberland** [comment]
Yes, it's fixed in the arccheck_nm branch.
